include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - "**/*.g.dart"
    - lib/l10n/app_localizations*.dart

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    require_trailing_commas: false
